# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=40)),
                ('theoryClass', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=60)),
                ('studentGrade', models.CharField(max_length=40)),
                ('studentSubject', models.CharField(max_length=40)),
                ('studentNumber', models.IntegerField()),
                ('needAssistant', models.BooleanField(default=True)),
                ('extra', models.TextField(blank=True)),
                ('experimentTotalCourePeriod', models.IntegerField(blank=True, default=0)),
                ('experimentTotalCourseCount', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.LabModel')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermWeekModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(blank=True, max_length=20)),
                ('lab', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickName', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='courseType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.CourseTypeModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='courseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.CourseModel'),
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.LessonModel'),
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.RoomModel'),
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='termWeek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.TermWeekModel'),
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.WeekModel'),
        ),
    ]
