# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXPS', '0002_auto_20170201_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
    ]
