# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXPS', '0003_auto_20170201_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetypemodel',
            old_name='abbr',
            new_name='nickName',
        ),
    ]
