# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EXPS', '0004_auto_20170201_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXPS.LabModel')),
            ],
        ),
        migrations.AddField(
            model_name='arrangementmodel',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EXPS.Assistant'),
        ),
    ]
