# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXPS', '0005_auto_20170202_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistant',
            new_name='AssistantModel',
        ),
    ]
