# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EXPS', '0006_auto_20170202_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EXPS.RoomModel'),
        ),
    ]
